### ISSUE TITLE
takeout enable soketi not working out of the box

### ISSUE THREAD

**Issue by scheMeZa** [tighten/takeout#318]
Run `takeout enable soketi`:
![image](https://github.com/tighten/takeout/assets/7773361/c9d0f535-10c8-4444-97f8-d7222257bf80)

Soketi cannot run however:
![image](https://github.com/tighten/takeout/assets/7773361/1da63545-dd7a-4f45-a94e-952fca8f9bb7)
2023-05-27 10:43:12 /app/node_modules/uWebSockets.js/uws.js:22
2023-05-27 10:43:12             throw new Error('This version of uWS.js supports only Node.js 14, 16 and 18 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).\n\n' + e.toString());
2023-05-27 10:43:12             ^
2023-05-27 10:43:12 
2023-05-27 10:43:12 Error: This version of uWS.js supports only Node.js 14, 16 and 18 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).
2023-05-27 10:43:12 
2023-05-27 10:43:12 Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/node_modules/uWebSockets.js/uws_linux_x64_93.node)
2023-05-27 10:43:12     at /app/node_modules/uWebSockets.js/uws.js:22:9
2023-05-27 10:43:12     at Object.<anonymous> (/app/node_modules/uWebSockets.js/uws.js:24:3)
2023-05-27 10:43:12     at Module._compile (node:internal/modules/cjs/loader:1191:14)
2023-05-27 10:43:12     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
2023-05-27 10:43:12     at Module.load (node:internal/modules/cjs/loader:1069:32)
2023-05-27 10:43:12     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
2023-05-27 10:43:12     at Module.require (node:internal/modules/cjs/loader:1093:19)
2023-05-27 10:43:12     at require (node:internal/modules/cjs/helpers:108:18)
2023-05-27 10:43:12     at Object.<anonymous> (/app/dist/server.js:18:13)
2023-05-27 10:43:12     at Module._compile (node:internal/modules/cjs/loader:1191:14)

**Comment by tonysm** [comment]
Thanks for reporting it. I've pushed a [PR](https://github.com/tighten/takeout/pull/322) to fix this by using the same tag as Laravel Sail uses (latest-16-alpine).
